blog/urls.py
from django.urls import path, include
from blog.views import Home, CreatePost, PostDetail, EditPost, ListPosts,AddLike,RemoveLike, uploadImage, uploadLinkView
from django.views.decorators.csrf import csrf_exempt

app_name = "blog"
urlpatterns = [
    path('',Home.as_view(),name = 'home'),
    path('blogs/',ListPosts.as_view(),name="postList"),
    path('<int:id>/',PostDetail.as_view(),name = 'postDetail'),
    path('create/',CreatePost.as_view(),name = 'postCreate'),
    path('edit/<int:id>/', EditPost.as_view(),name = 'postEdit'),
    path('uploadImage/',csrf_exempt(uploadImage), name = 'uploadImage'),
    path('linkfetching/',uploadLinkView),
    path('like/<int:id>', AddLike.as_view(),name="likeAPost"),
    path("unlike/<int:id>",RemoveLike.as_view(),name="unlikeAPost"),
]

hard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls"), name="blog-home"),
    path("users/", include("users.urls"), name="users-home"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from django_editorjs import EditorJsField


class Post(models.Model):
    title = models.CharField(max_length=60)
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like = models.ManyToManyField(
        settings.AUTH_USER_MODEL, through="Likes", related_name="liked_posts"
    )
    body = EditorJsField(
        editorjs_config={
            "tools": {
                "Link": {"config": {"endpoint": "/blog/linkfetching/"}},
                "Image": {
                    "config": {
                        "endpoints": {
                            "byFile": "/blog/uploadImage/",
                            "byUrl": "/blog/uploadImage/",
                        },
                    }
                },
            }
        }
    )

    def __str__(self):
        return f"{self.title}({self.id})"


class Likes(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("post", "user")

    def __str__(self):
        return f"{self.user.username}  liked {self.post.title}({self.post.id})."

blog/forms.py
from django import forms
from blog.models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','body']

blog/views.py
import json
from datetime import date, datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import serializers
from django.core.files.storage import FileSystemStorage
from django.db.utils import IntegrityError
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt, requires_csrf_token
from django.views.generic import DetailView, ListView

from .forms import PostCreateForm
from .models import Likes, Post


def json_serial(obj):
    if isinstance(obj, (datetime, date)):
        return obj.isoformat()
    raise TypeError(f"Type {type(obj)} is not serializable.")


class Home(ListView):
    model = Post
    template_name = "blog/index.html"

    def get(self, request):
        postList = Post.objects.all()
        likes = list()
        if request.user.is_authenticated:
            rows = request.user.liked_posts.values("id")
            likes = [row["id"] for row in rows]
        ctx = {"postList": postList, "likes": likes}
        return render(request, self.template_name, ctx)


class CreatePost(LoginRequiredMixin, View):
    template_name = "blog/postForm.html"
    success_url = reverse_lazy("blog:home")

    def get(self, request):
        form = PostCreateForm()
        ctx = {"form": form}
        return render(request, self.template_name, ctx)

    def post(self, request):
        form = PostCreateForm(request.POST)
        if not form.is_valid():
            ctx = {"form": form}
            return render(request, self.template_name, ctx)

        post = form.save(commit=False)
        post.user = self.request.user
        post.save()
        form.save_m2m()
        messages.success(request, f"Submitted successfully {post}")
        return redirect(self.success_url)


class EditPost(LoginRequiredMixin, View):
    template_name = "blog/postForm.html"
    success_url = reverse_lazy("blog:home")

    def get(self, request, id):
        post = get_object_or_404(Post, id=id, user=self.request.user)
        form = PostCreateForm(instance=post)
        ctx = {"form": form}
        return render(request, self.template_name, ctx)

    def post(self, request, id):
        post = get_object_or_404(Post, id=id, user=self.request.user)
        form = PostCreateForm(request.POST, instance=post)

        if not form.is_valid():
            ctx = {"form": form}
            return render(request, self.template_name, ctx)

        post = form.save(commit=False)
        post.save()
        form.save_m2m()
        messages.success(request, f"Edited successfully {post}")
        return redirect(self.success_url)


class ListPosts(LoginRequiredMixin, View):
    template_name = "blog/listPosts.html"

    def get(self, request):
        posts = Post.objects.filter(user=self.request.user).values(
            "user__username", "user__myuser__image", "title", "body", "createdAt","user","updatedAt","id"
        )
        postsJson = json.dumps(list(posts), default=json_serial)
        return render(request, self.template_name, {"postList": postsJson})


class PostDetail(DetailView):
    model = Post
    template_name = "blog/blogDetail.html"

    def get(self, request, id):
        post = Post.objects.get(id=id)
        ctx = {"post": post}
        return render(request, self.template_name, ctx)


@requires_csrf_token
def uploadImage(request):
    f = request.FILES["image"]
    fs = FileSystemStorage()
    filename = str(f).split(".")[0]
    file = fs.save(filename, f)
    fileurl = fs.url(file)
    return JsonResponse({"success": 1, "file": {"url": fileurl}})


def uploadLinkView(request):
    import requests
    from bs4 import BeautifulSoup

    print(request.GET["url"])
    url = request.GET["url"]
    response = requests.get(url)
    soup = BeautifulSoup(response.text, features="html.parser")
    metas = soup.find_all("meta")
    description = ""
    title = ""
    image = ""
    for meta in metas:
        if "property" in meta.attrs:
            if meta.attrs["property"] == "og:image":
                image = meta.attrs["content"]
        elif "name" in meta.attrs:
            if meta.attrs["name"] == "description":
                description = meta.attrs["content"]
            if meta.attrs["name"] == "title":
                title = meta.attrs["content"]
    return JsonResponse(
        {
            "success": 1,
            "meta": {
                "description": description,
                "title": title,
                "image": {"url": image},
            },
        }
    )


@method_decorator(csrf_exempt, name="dispatch")
class AddLike(LoginRequiredMixin, View):
    def post(self, request, id):
        print("hello")
        p = get_object_or_404(Post, id=id)
        like = Likes(user=request.user, post=p)
        try:
            like.save()
        except IntegrityError:
            pass
        return HttpResponse()


@method_decorator(csrf_exempt, name="dispatch")
class RemoveLike(LoginRequiredMixin, View):
    def post(self, request, id):
        print("hello")
        p = get_object_or_404(Post, id=id)
        try:
            like = Likes.objects.get(user=request.user, post=p).delete()
        except Likes.DoesNotExist:
            pass

        return HttpResponse()

templates/blog/blogDetail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Title Here {% endblock title %}

{% block body %}
<h2 id="h2ost-title">{{post.title}}</h2>
<a href="{% url 'blog:postEdit' post.id%}">Edit</a>
<section id="post-body"></section>
<script>
  window.addEventListener("DOMContentLoaded", () => {
    const postBody = document.getElementById("post-body");
    console.log("{{post.body|escapejs}}");
    let body = JSON.parse("{{post.body|escapejs}}");
    let blocks = body.blocks;
    console.log(blocks.length);

    for (let index = 0; index <= blocks.length; index++) {
      console.log(blocks[index], index);

      switch (blocks[index].type) {
        case "Header":
          let head = document.createElement(`h${blocks[index].data.level}`);
          head.textContent = blocks[index].data.text;
          postBody.appendChild(head);
          break;

        case "Image":
          let div = document.createElement("div");
          let image = document.createElement("img");
          let caption = document.createElement("small");
          image.src = `${blocks[index].data.file.url}`;
          image.style = "margin-top:10px;";
          image.height = 200;
          image.width = 200;
          caption.textContent = blocks[index].data.caption;
          caption.style = "margin-top:5px;";
          div.appendChild(image);
          div.appendChild(caption);
          div.style = "width:30%;display:grid;place-items:center";
          postBody.appendChild(div);
          break;

        case "List":
          let list;
          if (blocks[index].data.style == "unordered") {
            list = document.createElement("ul");
          } else {
            list = document.createElement("ol");
          }
          for (const item in blocks[index].data.items) {
            let li = document.createElement("li");
            li.textContent = blocks[index].data.items[item];
            list.appendChild(li);
          }
          postBody.appendChild(list);
          break;

        case "Raw":
          let blockquote = document.createElement("blockquote");
          let code = document.createElement("code");
          let pre = document.createElement("pre");
          pre.textContent = blocks[index].data.html;
          pre.style.background = "#131313";
          pre.style.color = "#dddddd";
          pre.style.padding = "15px";
          code.appendChild(pre);
          postBody.appendChild(code);
          break;

        case "Attaches":
          let parent = document.createElement("div");
          parent.style =
            "margin-top:10px;width:30%; padding:10px; border:1px solid black;border-radius:8px;";
          let a = document.createElement("a");
          let name = document.createElement("h4");
          a.href = `${blocks[index].data.file.url}`;
          a.textContent = `Download ${blocks[index].data.file.extension} (${
            blocks[index].data.file.size / 1000
          } kb)`;
          a.style = "grid-column: 1 / span 2";
          name.textContent = blocks[index].data.file.name;

          parent.appendChild(name);
          parent.appendChild(a);

          postBody.appendChild(parent);
          break;

        case "paragraph":
          const p = document.createElement("p");
          p.innerHTML = blocks[index].data.text;
          postBody.appendChild(p);
          break;

        case "Link":
          let parent2 = document.createElement("div");
          let a2 = document.createElement("a");
          parent2.style =
            " margin-top:10px; width:30%;display:grid; grid-template-columns: 1fr 50px; padding:10px; border:1px solid black;border-radius:8px;";

          if (blocks[index].data.meta.title) {
            let title = document.createElement("p");
            title.textContent = blocks[index].data.meta.title;
            parent2.appendChild(title);
          }
          if (blocks[index].data.meta.image.url !== "") {
            let parent3 = document.createElement("div");
            let img = document.createElement("img");

            img.src = blocks[index].data.meta.image.url;
            parent3.style = " display:grid;place-items:center";

            img.height = 40;
            img.width = 40;
            parent3.appendChild(img);
            parent2.appendChild(parent3);
          }

          if (blocks[index].data.meta.description) {
            let desc = document.createElement("small");
            desc.style = "grid-column: 1 / span 2";
            desc.textContent = blocks[index].data.meta.description;
            parent2.appendChild(desc);
          }
          a2.style = "text-decoration:none;color:black";
          a2.href = blocks[index].data.link;
          a2.appendChild(parent2);
          postBody.appendChild(a2);
          break;

        default:
          break;
      }
    }
  });
</script>
{% endblock body %}

templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Home {% endblock title %}

{% block body %}
{% if postList %}
<ul>
    {% for post in postList %}
        <li>
            <a href = "{% url 'blog:postDetail' post.id%}">{{ post.title }}</a>
            {% if user.is_authenticated %}
            <a href="#" onclick="toggleLike('{% url 'blog:likeAPost' post.id %}', {{post.id}});return false;"{% if post.id  in likes %} style="display: none;"{% endif %} id="like_{{post.id}}">
                <span class="fa-stack" style="vertical-align: middle;">
                    <i class="fa fa-heart fa-stack-1x" style="display: none; color: red;"></i>
                    <i class="fa fa-heart-o fa-stack-1x"></i>
                    </span>            
            </a>
            <a href="#" onclick="toggleLike('{% url 'blog:unlikeAPost' post.id %}', {{post.id}});return false;"{% if post.id not in likes %} style="display: none;"{% endif %} id="unlike_{{post.id}}">
                <span class="fa-stack" style="vertical-align: middle;">
                    <i class="fa fa-heart fa-stack-1x" style="color: red;"></i>
                    <i class="fa fa-heart-o fa-stack-1x"></i>
                    </span>
            </a>
            {% endif %}
        </li>
    {% endfor %}
</ul>
{% else %}
<p><a href="{% url 'blog:postCreate' %}">Be the first one to post.</a></p>
{% endif %}
<script>
    function toggleLike(url, postId){
        console.log(url);
    fetch(url,{
        method:"POST",
    }).then(() => {
        toggleHide(document.getElementById("like_"+postId))
        toggleHide(document.getElementById("unlike_"+postId))
    }).catch(console.error)
    }

    function toggleHide(element){
        if (!element.style.display)
            element.style.display = "none"
        else
            element.style.display =""
    }
</script>
{% endblock body %}

templates/blog/listPosts.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Blogs {% endblock title %}
{% block body %}
{% if postList %}
<div id="posts-container"></div>
{% else %}
<p><a href="{% url 'blog:postCreate' %}">Create your first post.</a></p>
{% endif %}
<script>
  window.addEventListener("DOMContentLoaded",addArticles)

function addArticles(){
  const postsContainer = document.getElementById("posts-container");
  if(!postsContainer)return null;
  const postList = JSON.parse("{{postList|escapejs}}");
  for(const post of postList)
  {
    console.log(post)
    const blocks = (JSON.parse(post.body)).blocks
    let paragraph;
    let img;
    for(let i = 0; i < blocks.length; i++){
      switch(blocks[i].type){
        case "paragraph":
          if(!paragraph)
          {
          const p = document.createElement("p");
          p.innerHTML = blocks[i].data.text;
          p.classList.add("post-content")
          paragraph = p
          }
          break;

        case "Image":
          if(!img){
            let image = document.createElement("img")
            image.src = `${blocks[i].data.file.url}`
            image.classList.add("post-thumbnail")
            img = image;
          }
          break;
      }
    }
    const node = document.createElement("div")
    const c1 = document.createElement("div")
    const c2 = document.createElement("div")
    const c3 = document.createElement("div")
    c1.classList.add("container-item-1")
    c2.classList.add("container-item-2")
    c3.classList.add("user-name-pic")
    node.classList.add("container-item")
    const username  = document.createElement("a")
    username.href = "#"
    username.textContent = post.user__username
    username.classList.add("user-link")
    const userPic = document.createElement("img")
    userPic.src = `/media/${post.user__myuser__image}`
    userPic.classList.add("profile-pic")
    const title = document.createElement("h3")
    title.innerHTML = `<a href="blog/${post.id}">${post.title}</a>`
    title.classList.add("post-heading")
    c3.appendChild(userPic)
    c3.appendChild(username)
    c1.appendChild(c3)
    c1.appendChild(title)
    if(paragraph)c1.appendChild(paragraph)
    node.appendChild(c1)
    if(img){
      c2.appendChild(img)
      node.appendChild(c2)
    }
    postsContainer.appendChild(node);
  }
}
</script>
{% endblock body %}

templates/blog/postForm.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Title Here {% endblock title %}

{% block body %}
 <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    <div class="form-control">{{form.as_p}}</div>

        <button>Submit</button>
 </form>
{% endblock body %}