blog/urls.py
from django.urls import path, include
from blog.views import Home, CreatePost, PostDetail, EditPost, ListPosts,AddLike,RemoveLike, uploadImage, uploadLinkView
from django.views.decorators.csrf import csrf_exempt

app_name = "blog"
urlpatterns = [
    path('',Home.as_view(),name = 'home'),
    path('blogs/',ListPosts.as_view(),name="postList"),
    path('<int:id>/',PostDetail.as_view(),name = 'postDetail'),
    path('create/',CreatePost.as_view(),name = 'postCreate'),
    path('edit/<int:id>/', EditPost.as_view(),name = 'postEdit'),
    path('uploadImage/',csrf_exempt(uploadImage), name = 'uploadImage'),
    path('linkfetching/',uploadLinkView),
    path('like/<int:id>', AddLike.as_view(),name="likeAPost"),
    path("unlike/<int:id>",RemoveLike.as_view(),name="unlikeAPost"),
]

hard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls"), name="blog-home"),
    path("users/", include("users.urls"), name="users-home"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}Core{% endblock title %}</title>

    <!-- Font Awesome Symbols -->
    <script src="https://kit.fontawesome.com/23d4421331.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="navbar">
        <div class="side-navbar left-navbar">
            <div class="side-navbar-element logo">
                <a href="{% url 'blog:home' %}">
                    <img class="img-logo" src="{% static 'images/hard_logo.jpg' %}" alt="Error">
                </a>
            </div>
            <div class="side-navbar-element">
                <form class="form search-form" method="">
                    <input type="text" class="form-text-box" placeholder="Search hard">
                    <input type="submit" value="Search">
                </form>
            </div>
        </div>
        {% if user.is_authenticated %}
        <div class="side-navbar right-navbar">
            <div class="side-navbar-element write-blog">
                <a href="{% url 'blog:postCreate' %}">Write</a>
            </div>
            <div class="side-navbar-element div-profile-pic">
                <a href="{% url 'user-profile' %}">
                    <img src="{{user.myuser.image.url}}" class="profile-pic" alt="">
                </a>
            </div>
        </div>
        {% else %}
        <div class="side-navbar right-navbar">
            <div class="side-navbar-element write-blog">
                <a href="{% url 'user-register' %}">Register</a>
            </div> | 
            <div class="side-navbar-element write-blog">
                <a href="{% url 'user-signin' %}">Sign-in</a>
            </div>
        </div>
        {% endif %}
    </div>
    <div class="main-body">
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "error" %}
                    <div class="alert-danger message">
                {% elif message.tags == "debug" %}    
                    <div class="alert-dark message">
                {% else %}
                    <div class="alert-{{message.tags}} message">
                {% endif %}
                    {{message}}
                    </div>
            {% endfor %}
        {% endif %}

        {% block body %}
        {% endblock body %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    </div>
</body>
</html>